allow publish from other branch

diff --git a/.github/workflows/build-publish.yaml b/.github/workflows/build-publish.yaml
--- a/.github/workflows/build-publish.yaml
+++ b/.github/workflows/build-publish.yaml
@@ -47,11 +47,11 @@ jobs:
           echo "SHA of current branch: ${{ env.SHA_OF_CURRENT_BRANCH }}"
           echo "SHA of main branch: ${{ env.SHA_OF_MAIN_BRANCH }}"
 
-      - name: Fail if attempting to publish to prod release channel incorrectly
-        if: github.event.inputs.release_channel == 'prod'
-        run: |
-          if [ "${{github.event.inputs.api_endpoint}}" = "prod" ] ; then echo "Using prod API endpoint, can proceed to publish"; else exit 1; fi
-          if [ "${{ env.SHA_OF_CURRENT_BRANCH }}" = "${{ env.SHA_OF_MAIN_BRANCH }}" ] ; then echo "Running on main branch, can proceed to publish"; else exit 1; fi
+      # - name: Fail if attempting to publish to prod release channel incorrectly
+      #   if: github.event.inputs.release_channel == 'prod'
+      #   run: |
+      #     if [ "${{github.event.inputs.api_endpoint}}" = "prod" ] ; then echo "Using prod API endpoint, can proceed to publish"; else exit 1; fi
+      #     if [ "${{ env.SHA_OF_CURRENT_BRANCH }}" = "${{ env.SHA_OF_MAIN_BRANCH }}" ] ; then echo "Running on main branch, can proceed to publish"; else exit 1; fi
 
   publish:
     needs: [check_inputs]
